### ISSUE TITLE
Compile ready versions?

### ISSUE THREAD

**Issue by kgashok** [rajasekaranap/Pet-Talk-Abstract-Java#4]
All source code files must compile successfully in the Java compiler. Please double check.

**Comment by rajasekaran36** [comment]
Extended to Parrot - Checked and Working
https://github.com/rajasekaranap/Pet-Talk-Abstract-Java/blob/master/src/ParrotMain.java
All Pets are Anonymous ( Refactored code ) - Checked and Working
https://github.com/rajasekaranap/Pet-Talk-Abstract-Java/blob/master/src/PetFullAnonymous.java
Pets with Code - Checked and Working
https://github.com/rajasekaranap/Pet-Talk-Abstract-Java/blob/master/src/PetsWithCode.java
