### ISSUE TITLE
Comments for all the three versions

### ISSUE THREAD

**Issue by kgashok** [rajasekaranap/Pet-Talk-Abstract-Java#5]
Provide suitable comments so it is easy for the trainer to use and explain.

**Comment by rajasekaranap** [comment]
Extended to Parrot - Checked and Working 
[https://github.com/rajasekaranap/Pet-Talk-Abstract-Java/blob/master/src/ParrotMain.java](url)
All Pets are Anonymous ( Refactored code )  - Checked and Working 
[https://github.com/rajasekaranap/Pet-Talk-Abstract-Java/blob/master/src/PetFullAnonymous.java](url)
Pets with Code -  Checked and Working
[https://github.com/rajasekaranap/Pet-Talk-Abstract-Java/blob/master/src/PetsWithCode.java](url)

**Comment by rajasekaran36** [comment]
Comments Added for all codes Sir.. Kindly have look sir
